### ISSUE TITLE
Code Formatting

### ISSUE THREAD

**Issue by chris-ricketts** [thespis-rs/thespis#1]
Hi, 

I'm interested in the project and its goals.
I've started reading the code to get an understanding of how it works. However, the non-standard code formatting is making it harder to read (on Github anyway).

Would you be open to using the standard Rust formatting? 
It can be sorted very quickly with [rustfmt](https://github.com/rust-lang/rustfmt).

It would also make it easier for people to contribute.

**Comment by najamelan** [comment]
I'm sorry to hear that you have difficulty reading my formatting style. I can relate, because for me code formatted with rustfmt is very straining. Is the problem you are having related to line length? I do sometimes make lines quite long when it avoids wrapping several almost identical lines, but if your screen is smaller, the automatic wraps will be annoying I admit.

As for the rest, I wonder if it might be harder to read just because you aren't used to this style of formatting? In general I try to represent the structure of the code visually, which should read easier. Have a look a the following code from the an example of hyper. I introduced the same bug in both versions. Which formatting allows you to spot the bug more easily?

This is code formatted with rustfmt:

```rust
fn response_examples(req: Request<Body>) -> ResponseFuture {
    match (req.method(), req.uri().path()) {
        (&Method::GET, "/") | (Method::GET, "/index.html") | (&Method::GET, "/big_file.html") => {
            simple_file_send(INDEX)
        }
        (&Method::GET, "/no_file.html") => {
            // Test what happens when file cannot be be found
            simple_file_send("this_file_should_not_exist.html")
        }
        _ => Box::new(future::ok(
            Response::builder()
                .status(StatusCode::NOT_FOUND)
                .body(Body::empty())
                .unwrap(),
        )),
    }
}
```



This code uses structural formatting:

```rust
fn response_examples( req: Request<Body> ) -> ResponseFuture
{
   match ( req.method(), req.uri().path() )
   {

      ( &Method::GET, "/"              )  |
      (  Method::GET, "/index.html"    )  |
      ( &Method::GET, "/big_file.html" ) => simple_file_send( INDEX ),


      // Test what happens when file cannot be be found
      //
      ( &Method::GET, "/no_file.html"  ) => simple_file_send( "this_file_should_not_exist.html" ),


      _ =>  Box::new( future::ok
            (
               Response::builder()
            
                  .status( StatusCode::NOT_FOUND )
                  .body  ( Body::empty()         )
                  .unwrap()
            ))
   }
}
```

Note that the library is still very much under development, so the code will be cleaner by the time I publish it. 

Since I can't read code that does not have spacious formatting, I won't rustfmt code I have to maintain. If it's more comfortable for you to read, I suggest you rustfmt files before reading them. That's relatively low effort. I haven't come round to making a code formatting tool, so I generally have to reformat code by hand before reading it.

**Comment by chris-ricketts** [comment]
Fair enough, I'll admit that the missing '&' was easier to see with your formatting style.
Although, if you set `max_width = 80` for rustfmt instead of the default 100 you get:
```rust
fn response_examples(req: Request<Body>) -> ResponseFuture {
    match (req.method(), req.uri().path()) {
        (&Method::GET, "/")
        | (Method::GET, "/index.html")
        | (&Method::GET, "/big_file.html") => simple_file_send(INDEX),
        (&Method::GET, "/no_file.html") => {
            // Test what happens when file cannot be be found
            simple_file_send("this_file_should_not_exist.html")
        }
        _ => Box::new(future::ok(
            Response::builder()
                .status(StatusCode::NOT_FOUND)
                .body(Body::empty())
                .unwrap(),
        )),
    }
}
```
I'll just clone the repos and format the code before reading through it, I'm too used to the standard now that I find anything as different as your style quite distracting.

I feel for you having to do all that formatting by hand - maybe you could setup a [custom rustfmt configuration](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md) at some point to get as near as you can to your style? It would save you time and future contributors could use it to keep everything the same. 

Thanks for answering my question so thoroughly anyway. I'll close the issue.

**Comment by oleid** [comment]
What matters most for me is having automatic code formatting. I don't care too much about the style. As soon as you have multiple people working on the same codebase, reviewing the formatting as well is a PITA, IMHO.
