### ISSUE TITLE
Why not use a Cargo Workspace?

### ISSUE THREAD

**Issue by njam** [thespis-rs/thespis#2]
Is there a reason why you're using git submodules and not multiple Cargo packages in a single repo with a [Cargo workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html)?

Example repo - serde: https://github.com/serde-rs/serde

I have the feeling for this use case it would be easier to work with the code?

**Comment by najamelan** [comment]
To be honest, every time I have tried to use workspaces it has been such a PITA that I kind of gave up on that feature. It also means that my brain didn't store all the particular issues I encountered, but a few that come to my mind are:

- everything always has to compile together (eg. If you are working on a crate and leave it in a not-compiling state, you can't work on anything else unless you remove it from the workspace. For development this is a royal nuissance. You constantly find yourself commenting in and out the different crates)
- you can't combine crates meant for different targets. If some of your crates are meant for WASM and need to build with `wasm-pack build`, you can't use a workspace. This particular issue does not occur in thespis though. 
- I fail to see the benefit. If you have crates in the same repository, with path dependencies, when you are focusing on a crate, cargo will compile all of it's dependencies just fine. I don't really see the benefit of a workspace here. AFAICT it's well adapted to the scenario where you want to build a big application and you have your components split in several crates. Where it doesn't make sense to compile the individual components because they won't build a working app. However in thespis it's all libraries, which are meant for people to depend on individually. A lib might depend on the `_iface` crates, implement the traits and never use an implementation. Client code can chose any implementation, which might not be in this repository btw. It's also perfectly possible to use the actor implementation without ever using remote actors. So it doesn't make sense to me to always try to compile everything together.

I ran into other issues, but right now I can't remember. 

I understand that having things in sub-modules rather than one single repo adds some overhead to forking and committing stuff, but I really like to keep the git history of the several crates separate. The global crate keeps track of a state in which all submodules play nice together, yet we can evolve separate crates for development, and only commit those changes in the thespis repository when all crates are compatible. 

The global repository is just there to keep a place where there is global overiew of thespis. It will also include a repo for the user guide, allows cloning all those repositories in one go. It's important to me to be able to evolve every crate separately and be able to check out different versions of them individually. For all intends and purposes, consider that these are different crates.

The question of using submodules is actually orthogonal to the workspace.

**Comment by njam** [comment]
Ho, thanks for the detailed explanation! That wouldn't have been necessary. But thanks, appreciated! :)
